version: '3.7'
services:
  isla-test-api:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/usr/src/app
      ports:
        - 5002:5001
      environment:
        DEBUG: 'true'
      networks:
        isla-test-api-network:
          ipv4_address: 172.20.128.1
 
volumes:
  mongodb_dev: {}
  mongodb_test: {}
  redis: {}
networks:
  isla-test-api-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16