version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 5001
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5001
    # depends_on:
    #   - mongodb_test
    environment:
      MONGODB_URL:  mongodb://142.28.1.2:27017/test
      PASSWORD:  test
      DEBUG: 'true'
    networks:
      testing_net:
        ipv4_address: 142.28.1.1

  # mongodb_test:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   ports:
  #     - 27018:27017
  #   volumes:
  #     - mongodb_test:/data/db
  #   networks:
  #     testing_net:
  #       ipv4_address: 142.28.1.2

volumes:
  db_data: {}
  mongodb_test: {}
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 142.28.0.0/16