version: '3.7'
services:
  isla-test-api:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/usr/src/app
      ports:
        - 5002:8080
      environment:
        DEBUG: 'true'
      networks:
        isla-test-api-network:
          ipv4_address: 220.223.1.2
      extra_hosts:
      - host.docker.internal:host-gateway
 
volumes:
  mongodb_dev: {}
  mongodb_test: {}
  redis: {}
networks:
  isla-test-api-network:
    ipam:
      driver: default
      config:
        - subnet: 220.223.0.0/16