version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      my_network:
        ipv4_address: 142.29.0.2
    ports:
      - "3000:3000"

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 142.29.0.0/24
