version: '3'
services:
  tidal-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tidal-api
    restart: always
    ports:
      - "3000:3000"
    networks:
      tidal_network:
        ipv4_address: 10.10.1.5
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  tidal_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16
