version: 2.1

jobs:
   ci:
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: medium
    working_directory: ~/code

    steps:
      - checkout      
      - run:
          name: Build Docker Image
          command: |
            docker build -t test-image .

      - run:
          name: Run Docker Compose
          command: |
            docker-compose up -d
      - run:
          name: Install Newman
          command: npm install -g newman
      - run:
          name: Run Tests with Newman
          command: newman run ci-collection.json

      - persist_to_workspace:
          root: /tmp
          paths:
            - your-app-directory

workflows:
  version: 2
  ci-cd:
    jobs:
      - ci