name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@v1
        id: revieweeRequest
        with:
          url: "https://api.reviewee.it/repository/Islaevent-API/haveRejectedCommits"
          method: "GET"
      - run: "echo latest release: ${{ steps.revieweeRequest.outputs.response }}"
      - name: Reject build if rejected commits
        if: steps.revieweeRequest.outputs.response == {"success":true,"status":200,"meta":null}
        run: "echo asd"
