name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check rejected commits
        id: revieweeRequest
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: "https://api.reviewee.it/repository/Islaevent-API/haveRejectedCommits"
      - name: Reject build if rejected commits
        if: ${{ steps.revieweeRequest.outputs.response.success == 'false' }}
        run: exit 1
