name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET https://api.reviewee.it/repository/Islaevent-API/haveRejectedCommits
      - run: "echo latest release: ${{ steps.get_latest_release.outputs.response }}"

      - name: Check rejected commits
        id: revieweeRequest
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: "https://api.reviewee.it/repository/Islaevent-API/haveRejectedCommits"
      - name: Reject build if rejected commits
        if: ${{ steps.revieweeRequest.outputs.response.success == 'false' }}
        run: exit 1
