name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: JamesIves/fetch-api-data-action@v2.1.0
        id: revieweeRequest
        with:
          endpoint: "https://api.reviewee.it/repository/Islaevent-API/haveRejectedCommits"
          configuration: '{ "method": "GET"}'
      - run: "echo latest release: $fetch-api-data"

      - name: Reject build if rejected commits
        if: ${{ steps.revieweeRequest.outputs.response.success == 'true' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Please fix rejected commits')
