name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: revieweeRequest
        with:
          route: "GET https://api.reviewee.it/repository/Islaevent-API/haveRejectedCommits"
      - run: "echo latest release: ${{steps.revieweeRequest.outputs.data }}"

      - name: Reject build if rejected commits
        if: ${{ steps.revieweeRequest.outputs.response.success == 'true' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Please fix rejected commits')
