name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@v1
        id: revieweeRequest
        with:
          url: "https://api.reviewee.it/repository/Islaevent-API/haveRejectedCommits"
          method: "GET"
      - run: steps.revieweeRequest.outputs.response.success == true && exit 1
