name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: JamesIves/fetch-api-data-action@v2.2.2
        id: revieweeRequest
        with:
          endpoint: https://api.reviewee.it/repository/Islaevent-API/haveRejectedCommits
          configuration: '{ "method": "GET" }'

      - name: Reject build if rejected commits
        if: ${{ steps.revieweeRequest.outputs.response.success == true }}
        run: exit 1
